### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by adhsu** [drhurdle/node-rethinkdb-auth-starter#2]
Thanks, found it via reddit. Would be dope if you also built it using Koa since that seems to be superseding Express.

**Comment by drhurdle** [comment]
Appreciate the feedback.  I haven't worked with Koa much but rewriting this would probably be a good exercise in getting more familiar.  I'll let you know and close this when its finished.  I have a few more features i'd like to add as well.  Will probably update this after
