### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ademayo** [drhurdle/node-rethinkdb-auth-starter#7]
Not really an "issue," but I wasn't sure where else to ask this. Is this repo MIT licensed? It appears that way from the package.json

**Comment by drhurdle** [comment]
Sorry it took a while to get to this.  Haven't been around in a bit.  Yes it is MIT.  Use it as you wish.  I do feel like its a bit outdated and there are some other things that are probably needed for it but it may be a good starting point to go off of.
